### ISSUE TITLE
Fail to generate all-time-stats.json

### ISSUE THREAD

**Issue by Jerry-Jzy** [Ahmedazim7804/trakt_vip_stats#1] opened 2024-01-31 04:48 UTC
After run 

> python main.py update movies --save

pop up the errors/warnings as follows:

- First 

<img width="1492" alt="image" src="https://github.com/Ahmedazim7804/trakt_vip_stats/assets/66828815/3b3d4192-7bfa-4332-a272-7445fcf6934b">
Another error about time zoon conflict was found here. I watched Episode 25 of "Blossoms Shanghai" on Jan 17th 12:03AM, But it showed  ["2024-01-16T16:03:07.000Z"]

- Second

<img width="1487" alt="image" src="https://github.com/Ahmedazim7804/trakt_vip_stats/assets/66828815/78abbe23-037b-415b-99c1-e635072e4d8c">

- Third

<img width="1417" alt="image" src="https://github.com/Ahmedazim7804/trakt_vip_stats/assets/66828815/f00bc1b5-f656-4906-a949-1cbc5f1d5a23">

Running os: MasOS 14.3
Python version: 3.9.7

**Comment by Ahmedazim7804** [comment] 2024-01-31 16:27
Thanks for the issue.
Does the program stop at 1st and 2nd error? or it continue till the 3rd and then crashes?

**Comment by Jerry-Jzy** [comment] 2024-01-31 16:47
> Thanks for the issue. Does the program stop at 1st and 2nd error? or it continue till the 3rd and then crashes?

stop at 3rd. 1st and 2nd are warnings

**Comment by Ahmedazim7804** [comment] 2024-01-31 17:10
Yes then, 1st is intended behaviour, it skips item for which tmdb does not have important data like runtime here. Its okay and will not cause any problem.

The 2nd is either api limit exceeding (should not happen as you do not have that much data here) or item completely does not exist in tmdb database.

3rd one is about multiprocessing, and seems to be unique to mac os. i dont have any mac machine.
i will try to fix if i can.

**Comment by Ahmedazim7804** [comment] 2024-01-31 17:10
Also on re-running the program, does 3rd error occur again and crashes?

**Comment by Jerry-Jzy** [comment] 2024-01-31 17:30
> Also on re-running the program, does 3rd error occur again and crashes?

yes

**Comment by Jerry-Jzy** [comment] 2024-01-31 17:34
> Yes then, 1st is intended behaviour, it skips item for which tmdb does not have important data like runtime here. Its okay and will not cause any problem.
> 
> The 2nd is either api limit exceeding (should not happen as you do not have that much data here) or item completely does not exist in tmdb database.
> 
> 3rd one is about multiprocessing, and seems to be unique to mac os. i dont have any mac machine. i will try to fix if i can.

Thank you

**Comment by Ahmedazim7804** [comment] 2024-02-09 14:08
i have pushed some changes, please re-clone the repository and try again.

**Comment by Jerry-Jzy** [comment] 2024-02-09 16:07
> i have pushed some changes, please re-clone the repository and try again.

similar error
<img width="1509" alt="image" src="https://github.com/Ahmedazim7804/trakt_vip_stats/assets/66828815/b7627412-f46a-4773-b96e-049917b4863f">

**Comment by Ahmedazim7804** [comment] 2024-02-10 04:42
please pull the change (or re-clone the repo) and try again. it should be fixed now.

**Closed as completed** 2024-04-27 04:57 UTC
